// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yrrWP-01YO1313pV0WOzKFfqLXkYcAY',
    appId: '1:749841913217:web:9afba601e3e2c5d82b4480',
    messagingSenderId: '749841913217',
    projectId: 'crudfirebaseapp-33b3b',
    authDomain: 'crudfirebaseapp-33b3b.firebaseapp.com',
    storageBucket: 'crudfirebaseapp-33b3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4EwA8dGI5fuRO3mph2s_Y6nDBFk3yGo',
    appId: '1:749841913217:android:6fb9c8d5fb0841a22b4480',
    messagingSenderId: '749841913217',
    projectId: 'crudfirebaseapp-33b3b',
    storageBucket: 'crudfirebaseapp-33b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBbRGlQm4bBGZNcEh4zknX02pZu_kIfU',
    appId: '1:749841913217:ios:ea92ce450e5cffed2b4480',
    messagingSenderId: '749841913217',
    projectId: 'crudfirebaseapp-33b3b',
    storageBucket: 'crudfirebaseapp-33b3b.appspot.com',
    iosClientId: '749841913217-1p03tbct51ujnrstbn1drtkn0d7u9fd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBbRGlQm4bBGZNcEh4zknX02pZu_kIfU',
    appId: '1:749841913217:ios:ea92ce450e5cffed2b4480',
    messagingSenderId: '749841913217',
    projectId: 'crudfirebaseapp-33b3b',
    storageBucket: 'crudfirebaseapp-33b3b.appspot.com',
    iosClientId: '749841913217-1p03tbct51ujnrstbn1drtkn0d7u9fd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebaseapp',
  );
}
